services:
  - type: web
    name: loan-management-system
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://loan-management-system-r3w9.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        value: base64:fBLagyKY+55HaS14lY/vBIi1wNFmb1gyAc8kl7kEuuY=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: DB_DATABASE
        fromDatabase:
          name: lms-db
          property: database
      - key: DB_SSLMODE
        value: no-verify
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
    healthCheckPath: /up

databases:
  - name: lms-db
    plan: free
    databaseName: lms_db
    user: lms_user
    region: oregon
